"""Provider-neutral model IR, dialects, deployments, and compatibility aliases.

AI-Generated Code - Claude Fable 5 (Anthropic)
"""

from ._legacy_bridge import ModelCallMeta, ModelMeta, ModelOutput, ModelUsage
from .capabilities import (
    Capability,
    CapabilityKey,
    ModelCapabilityEntry,
    ModelCapabilityProfile,
    ModelCapabilityStatus,
    RequestDefaults,
)
from .chat_model import ChatModel
from .connection_factory import (
    ASYNC_HTTP_JSON_FACTORY,
    CONNECTION_FACTORY_REGISTRY,
    OPENAI_SDK_FACTORY,
    AsyncHTTPJSONConnection,
    ConnectionFactoryRegistry,
    ConnectionFactorySpec,
    ConnectionRequest,
    UnknownConnectionFamily,
)
from .deployment import (
    BINDING_RESOURCE_KEYS,
    ConnectionIdentity,
    ConnectionPool,
    Deployment,
    DeploymentPlanProjection,
    DeploymentTopology,
    Engine,
    ResolvedRoute,
    RouteIntent,
    ServingFacts,
)
from .dialect import Dialect, DialectError
from .dialect_registry import DialectSpec, bind_dialect, get_dialect_spec
from .exceptions import CapabilityError
from .gen_model import GenModel
from .ir import (
    CapabilityEvidence,
    ChatInput,
    ChatMessage,
    Citation,
    CompletionInput,
    ContentPart,
    DialectOptions,
    FunctionToolCall,
    GroundingChunk,
    GroundingMetadata,
    HostedToolSpec,
    ImagePart,
    InputScoringResult,
    ModelIdentity,
    ModelInput,
    ModelProvenance,
    OpaqueContinuation,
    ReasoningOutput,
    ReasoningParams,
    Request,
    Response,
    SamplingParams,
    SchedulingParams,
    ScoringParams,
    ServerToolSpec,
    ServerToolType,
    ServerToolUse,
    SessionParams,
    StructuredOutput,
    StructuredOutputParams,
    TextPart,
    TokenLogprob,
    ToolCallPart,
    ToolParams,
    ToolResultPart,
    TopKEntry,
    UsageStats,
    normalize_chat_input,
)
from .model import Model
from .reconcile import (
    BindingReconcileInput,
    ConnectionScope,
    DeploymentCapabilityPlan,
    DeploymentReconcileInput,
    ReconcileBatch,
    ReconcileDiagnostic,
    ReconcileResult,
    RuntimeBindingPlan,
    reconcile,
)
from .sglang_gen_model import SglangGenModel
from .transport import Transport

__all__ = [
    "BINDING_RESOURCE_KEYS",
    "Capability",
    "CapabilityEvidence",
    "CapabilityError",
    "CapabilityKey",
    "ChatModel",
    "ChatInput",
    "ChatMessage",
    "Citation",
    "CompletionInput",
    "CONNECTION_FACTORY_REGISTRY",
    "ConnectionIdentity",
    "ConnectionFactoryRegistry",
    "ConnectionFactorySpec",
    "ConnectionPool",
    "ConnectionRequest",
    "ConnectionScope",
    "ContentPart",
    "Deployment",
    "DeploymentCapabilityPlan",
    "DeploymentPlanProjection",
    "DeploymentReconcileInput",
    "DeploymentTopology",
    "Dialect",
    "DialectError",
    "DialectOptions",
    "DialectSpec",
    "Engine",
    "FunctionToolCall",
    "GenModel",
    "GroundingChunk",
    "GroundingMetadata",
    "HostedToolSpec",
    "ImagePart",
    "InputScoringResult",
    "Model",
    "ModelCallMeta",
    "ModelCapabilityEntry",
    "ModelCapabilityProfile",
    "ModelCapabilityStatus",
    "ModelIdentity",
    "ModelInput",
    "ModelMeta",
    "ModelOutput",
    "ModelProvenance",
    "ModelUsage",
    "OpaqueContinuation",
    "OPENAI_SDK_FACTORY",
    "ReasoningOutput",
    "ReasoningParams",
    "ReconcileBatch",
    "ReconcileDiagnostic",
    "ReconcileResult",
    "Request",
    "RequestDefaults",
    "ResolvedRoute",
    "Response",
    "RouteIntent",
    "RuntimeBindingPlan",
    "SamplingParams",
    "SchedulingParams",
    "ScoringParams",
    "ServerToolSpec",
    "ServerToolType",
    "ServerToolUse",
    "ServingFacts",
    "SessionParams",
    "SglangGenModel",
    "StructuredOutput",
    "StructuredOutputParams",
    "TextPart",
    "TokenLogprob",
    "ToolCallPart",
    "ToolParams",
    "ToolResultPart",
    "TopKEntry",
    "Transport",
    "UsageStats",
    "ASYNC_HTTP_JSON_FACTORY",
    "AsyncHTTPJSONConnection",
    "BindingReconcileInput",
    "bind_dialect",
    "get_dialect_spec",
    "normalize_chat_input",
    "reconcile",
    "UnknownConnectionFamily",
]
