"""
Deployment topology data models.

All models are frozen dataclasses. DeploymentPlan is the system's IR
(Intermediate Representation): generated by TopologyResolver, consumed
by BackendTranslator.

AI-Generated Code - Claude Opus 4.6 (Anthropic)
"""

from collections.abc import Mapping
from dataclasses import dataclass, field
from types import MappingProxyType
from typing import Any, Literal

from sieval.infer.config import ParamValue
from sieval.infer.params import merge_params


def _freeze_dict[K, V](d: Mapping[K, V]) -> MappingProxyType[K, V]:
    """Wrap a mapping in MappingProxyType to enforce frozen-dataclass contract."""
    return MappingProxyType(d)


class WellKnownRole:
    """Pre-defined role constants.

    Open strings, not enum -- different frameworks use different role names.
    """

    FULL = "full"
    PREFILL = "prefill"
    DECODE = "decode"
    ENCODER = "encoder"
    ROUTER = "router"


@dataclass(frozen=True)
class ParallelTopology:
    """Parallel strategy for a set of GPUs.

    Each field maps to one parallelism dimension.
    EP reuses TP x DP devices (does not add GPU count).
    CP reuses TP-group devices.
    """

    tp: int = 1
    dp: int = 1
    pp: int = 1
    ep: int | None = None
    enable_dp_attention: bool = False
    cp: int | None = None

    @property
    def gpu_count(self) -> int:
        """Minimum GPU requirement (EP/CP reuse existing devices)."""
        return self.tp * self.dp * self.pp

    def validate(self) -> list[str]:
        """Return list of validation errors (empty = valid)."""
        errors: list[str] = []
        for name, val in [("tp", self.tp), ("dp", self.dp), ("pp", self.pp)]:
            if val < 1:
                errors.append(f"{name} must be >= 1, got {val}")
        if self.ep is not None and self.tp >= 1 and self.dp >= 1:
            if self.ep < 1:
                errors.append(f"ep must be >= 1, got {self.ep}")
            elif self.ep > self.tp * self.dp:
                errors.append(f"ep({self.ep}) > tp*dp({self.tp * self.dp})")
            elif self.ep <= self.tp and self.tp % self.ep != 0:
                # sglang requires TP % EP == 0 (computes tp_size // ep_size)
                errors.append(f"tp({self.tp}) % ep({self.ep}) != 0")
            elif self.ep > self.tp and self.ep % self.tp != 0:
                # When EP > TP, framework computes ep_size // tp_size
                errors.append(f"ep({self.ep}) % tp({self.tp}) != 0")
        if self.cp is not None and self.cp < 1:
            errors.append(f"cp must be >= 1, got {self.cp}")
        # NOTE: no DPA tp%dp constraint — sglang's actual constraint is
        # total_tp % dp == 0, and total_tp = tp * dp, so it is always satisfied.
        return errors


@dataclass(frozen=True)
class DeviceGroup:
    """A group of physical/logical devices."""

    count: int
    gpu_model: str | None = None
    host: str = "localhost"


@dataclass(frozen=True)
class ServiceBinding:
    """External service binding (e.g. SiMM KV cache)."""

    kind: str  # "kv_cache", ...
    provider: str  # "simm", "redis", ...
    address: str  # "10.0.1.100:30001"
    options: Mapping[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        object.__setattr__(self, "options", _freeze_dict(self.options))


@dataclass(frozen=True)
class ScalingPolicy:
    """Scaling policy -- Phase 6 placeholder, not consumed by Phase 1-2."""

    min_replicas: int = 1
    max_replicas: int | None = None
    scale_unit_gpus: int | None = None
    max_disruption: Literal["hot", "warm", "cold"] = "hot"


@dataclass(frozen=True)
class RoleAssignment:
    """Complete deployment description for one role.

    engine_params carries non-parallel parameters from recipe profiles
    (dtype, max_model_len, gpu_memory_utilization, etc.). Each role can
    have different engine_params -- e.g. PD split with different hardware
    or different memory budgets per role. The translator appends these
    as CLI flags alongside the parallel topology flags.

    __post_init__ normalizes engine_params keys to underscore form and
    raises ValueError if the input dict contains both dash and underscore
    variants of the same normalized key (e.g. ``{"foo-bar": 1, "foo_bar": 2}``).
    """

    role: str
    devices: DeviceGroup
    topology: ParallelTopology
    replicas: int = 1
    engine_params: Mapping[str, ParamValue] = field(default_factory=dict)
    scaling: ScalingPolicy | None = None  # Phase 6 placeholder

    def __post_init__(self) -> None:
        normalized = merge_params(self.engine_params)
        object.__setattr__(self, "engine_params", _freeze_dict(normalized))

    def validate(self) -> list[str]:
        """Return list of validation errors (empty = valid)."""
        errors = self.topology.validate()
        needed = self.topology.gpu_count * self.replicas
        if self.devices.count < needed:
            errors.append(
                f"Role {self.role}: needs {needed} GPUs "
                f"(tp={self.topology.tp} x dp={self.topology.dp} "
                f"x pp={self.topology.pp} x replicas={self.replicas}) "
                f"but DeviceGroup only has {self.devices.count}"
            )
        if self.replicas < 1:
            errors.append(f"Role {self.role}: replicas must be >= 1")
        return errors


# Default seed for deterministic mode, shared by the session layer
# (per-request `args.seed`) and the infer layer (engine startup-time seed).
DETERMINISTIC_DEFAULT_SEED: int = 0


@dataclass(frozen=True)
class DeploymentPlan:
    """Complete deployment description -- the system's IR.

    Immutable. Generated by TopologyResolver, consumed by BackendTranslator.
    """

    checkpoint: str
    backend: str
    assignments: tuple[RoleAssignment, ...]
    attachments: tuple[ServiceBinding, ...] = ()
    deterministic: bool = False
    # Engine-level seed pinned under deterministic mode. User-supplied
    # `seed` / `random_seed` via `infer.overrides` takes precedence.
    # Always set (even when deterministic=False) so translators don't
    # need to guard against None; non-deterministic plans ignore it.
    seed: int = DETERMINISTIC_DEFAULT_SEED

    @property
    def is_disaggregated(self) -> bool:
        """True if the plan uses disaggregated roles (not just FULL)."""
        roles = {a.role for a in self.assignments}
        return roles != {WellKnownRole.FULL}

    @property
    def total_gpus(self) -> int:
        """Total GPU count across all assignments (including replicas)."""
        return sum(a.topology.gpu_count * a.replicas for a in self.assignments)

    def validate(self) -> list[str]:
        """Return list of validation errors (empty = valid)."""
        errors: list[str] = []
        if not self.assignments:
            errors.append("DeploymentPlan must have at least one assignment")
        for a in self.assignments:
            errors.extend(a.validate())
        # Cross-role: PD roles must be paired
        roles = {a.role for a in self.assignments}
        if WellKnownRole.PREFILL in roles and WellKnownRole.DECODE not in roles:
            errors.append("prefill role requires a matching decode role")
        if WellKnownRole.DECODE in roles and WellKnownRole.PREFILL not in roles:
            errors.append("decode role requires a matching prefill role")
        return errors


@dataclass(frozen=True)
class DeploymentCapabilities:
    """Deployment capabilities exposed from infer to eval side.

    Constructed by Deployer after all processes are ready.
    """

    api_base: str
    is_disaggregated: bool
    roles: tuple[str, ...]
    total_gpus: int
    endpoints: Mapping[str, str] = field(default_factory=dict)
    metrics_url: str | None = None

    def __post_init__(self) -> None:
        object.__setattr__(self, "endpoints", _freeze_dict(self.endpoints))


# --- Resolver inputs ---


@dataclass(frozen=True)
class ModelProfile:
    """Model structure info for topology resolution.

    Extends ModelIdentity with MoE fields and pre-computed bytes_per_param.
    """

    param_billions: float
    num_layers: int
    is_moe: bool = False
    num_experts: int | None = None
    bytes_per_param: float = 2.0
    family: str | None = None


@dataclass(frozen=True)
class HardwareEnv:
    """Hardware environment for topology resolution."""

    gpu_count: int
    gpu_model: str
    gpu_memory_mib: int
    nodes: int = 1
    gpus_per_node: int | None = None


@dataclass(frozen=True)
class UserHints:
    """User intent -- soft hints, not hard constraints.

    Explicitly set fields take highest priority, skipping auto-derivation.
    Parallel dimension fields mirror ParallelTopology -- every dimension
    that can be auto-derived should be overridable here.
    """

    optimize_for: Literal["throughput", "latency"] | None = None
    disaggregation: Literal["pd", "af", "epd"] | None = None
    role_overrides: Mapping[str, Mapping[str, ParamValue]] | None = None
    tp: int | None = None
    dp: int | None = None
    pp: int | None = None
    ep: int | None = None
    enable_dp_attention: bool | None = None  # None=auto, True/False=force
    cp: int | None = None  # Context Parallelism

    def __post_init__(self) -> None:
        if self.role_overrides is not None:
            frozen = {k: _freeze_dict(v) for k, v in self.role_overrides.items()}
            object.__setattr__(self, "role_overrides", _freeze_dict(frozen))


# --- Resolver outputs ---


@dataclass(frozen=True)
class ResolveStep:
    """One decision in the resolution process -- for explain output."""

    field: str
    value: int | bool | None
    reason: str
    source: Literal["auto", "recipe", "user_override"]


@dataclass(frozen=True)
class ResolveResult:
    """Resolution result + explainable steps."""

    plan: DeploymentPlan
    steps: tuple[ResolveStep, ...]


# --- Topology key constants ---

# Per-dimension key groups: canonical name first, then framework-specific aliases.
TP_KEYS: frozenset[str] = frozenset({"tp", "tp_size", "tensor_parallel_size"})
DP_KEYS: frozenset[str] = frozenset({"dp", "dp_size", "data_parallel_size"})
PP_KEYS: frozenset[str] = frozenset({"pp", "pp_size", "pipeline_parallel_size"})
EP_KEYS: frozenset[str] = frozenset({"ep", "ep_size"})
CP_KEYS: frozenset[str] = frozenset({"cp", "attn_cp_size"})
DPA_KEYS: frozenset[str] = frozenset({"enable_dp_attention"})

# Union of all topology keys.  Everything else in an overrides dict is
# treated as an engine param.
TOPO_KEYS: frozenset[str] = TP_KEYS | DP_KEYS | PP_KEYS | EP_KEYS | CP_KEYS | DPA_KEYS
