"""Characterization tests: the capability split must not move instruct output.

The fixture (``golden_recipe_profiles.json``, regenerated by
``_capture_golden.py``) records what every profile leaf resolved to before
``profiles`` was split into ``hardware`` + ``capabilities``. An instruct model
must still resolve to exactly the same parameters, because a resolved plan
reaches ``infer_plans.yaml`` and ``--resume`` compares that file byte-for-byte.

AI-Generated Code - Claude Opus 5 (1M context) (Anthropic)
"""

import json
from pathlib import Path

from sieval.infer.params import merge_params
from sieval.infer.recipes import (
    load_recipe,
    resolve_capability_profile,
    resolve_hardware_profile,
)

_GOLDEN = Path(__file__).parent / "golden_recipe_profiles.json"

# Recipes whose capability params sat *between* hardware params in the pre-split
# leaves, so hoisting them into their own layer necessarily moves them to the
# end. Content is unchanged; only key order differs. This is reachable only by
# resuming a pre-split run, which the resume version gate already rejects across
# the minor boundary this ships in — but the exception is pinned here so a
# future reorder cannot slip in unnoticed.
_KNOWN_REORDERED: frozenset[str] = frozenset({"gpt-oss-20b", "gpt-oss-120b"})


def _golden_records() -> list[dict]:
    return json.loads(_GOLDEN.read_text())


def _resolve_instruct(record: dict) -> dict:
    """Resolve a golden record's triple the way the instruct path now does."""
    recipe = load_recipe(record["recipe"])
    hardware = resolve_hardware_profile(
        recipe,
        record["hardware_key"],
        record["precision"],
        record["framework"],
    )
    capabilities = resolve_capability_profile(recipe, "instruct", record["framework"])
    return merge_params(hardware or {}, capabilities)


def test_golden_fixture_is_populated():
    records = _golden_records()
    assert len(records) == 168, "fixture drifted; regenerate with _capture_golden.py"
    assert all(r["params"] for r in records)


def test_instruct_resolution_preserves_pre_split_content():
    """Every triple resolves to the same parameters as before the split."""
    for record in _golden_records():
        expected = dict(record["params"])
        actual = _resolve_instruct(record)
        assert actual == expected, (
            f"{record['recipe']} {record['hardware_key']} "
            f"{record['precision']} {record['framework']}"
        )


def test_instruct_resolution_preserves_pre_split_order():
    """Key order is preserved except for the recipes documented above."""
    reordered: set[str] = set()
    for record in _golden_records():
        expected = [k for k, _ in record["params"]]
        actual = list(_resolve_instruct(record))
        if actual != expected:
            assert sorted(actual) == sorted(expected), (
                f"{record['recipe']}: order test saw a content diff"
            )
            reordered.add(record["recipe"])

    assert reordered == _KNOWN_REORDERED, (
        "set of reordered recipes changed; a resolved plan's key order moved, "
        "which breaks --resume byte matching"
    )


def test_base_resolution_omits_capability_params():
    """A base checkpoint inherits hardware params but no instruct behavior."""
    capability_keys = {
        "tool_call_parser",
        "enable_auto_tool_choice",
        "reasoning_parser",
    }
    checked = 0
    for record in _golden_records():
        recipe = load_recipe(record["recipe"])
        hardware = resolve_hardware_profile(
            recipe,
            record["hardware_key"],
            record["precision"],
            record["framework"],
        )
        base = merge_params(
            hardware or {},
            resolve_capability_profile(recipe, "base", record["framework"]),
        )
        assert not (capability_keys & set(base)), (
            f"{record['recipe']} leaked instruct capabilities into the base path"
        )
        # The hardware half must still be there — the split withholds behavior,
        # not memory/context sizing.
        assert base == (hardware or {})
        checked += 1
    assert checked == 168
